// AUTO-GENERATED by the content editor's export pipeline.
// Do not edit by hand — any changes here will be overwritten on the next
// editor save. Source of truth lives in the Supabase content tables.
// Schema: docs/content-schema-v0.1.md.
// Generated at 2026-06-03T12:39:16.869Z.

export const WIKI_ENTRIES = {};
