// AUTO-GENERATED by scripts/build-content.mjs.
// Do not edit by hand. Source of truth is the authoring JSON named below;
// rebuild with: node scripts/build-content.mjs <source>
// Schema: docs/content-schema-v0.1.md.
// Source: remnant_content_consolidated_rev2.json
// Generated at 2026-08-22T18:13:58.436Z.

export const WIKI_ENTRIES = {};
