// Renders a snapshot (from snapshot.js) into ES module file contents
// ready to be committed to the game repo. Flat shape per the spec:
// one file per content group, each exports a single object keyed by id.
// Nested children (choices on encounters, beats on quests, effects on
// choices) are inlined.

const HEADER = `// AUTO-GENERATED by the content editor's export pipeline.
// Do not edit by hand — any changes here will be overwritten on the next
// editor save. Source of truth lives in the Supabase content tables.
// Schema: docs/content-schema-v0.1.md.
`;

export function renderFiles(snapshot, { generatedAt = new Date() } = {}) {
  const stampLine = `// Generated at ${generatedAt.toISOString()}.\n\n`;

  return [
    {
      path: "src/game/content/world-encounters.js",
      content:
        HEADER +
        stampLine +
        `export const WORLD_ENCOUNTERS = ${stableStringify(byId(snapshot.worldEncounters))};\n`,
    },
    {
      path: "src/game/content/field-encounters.js",
      content:
        HEADER +
        stampLine +
        `export const FIELD_ENCOUNTERS = ${stableStringify(byId(snapshot.fieldEncounters))};\n`,
    },
    {
      path: "src/game/content/quests.js",
      content:
        HEADER +
        stampLine +
        `export const QUESTS = ${stableStringify(byId(snapshot.quests))};\n`,
    },
    {
      path: "src/game/content/wiki.js",
      content:
        HEADER +
        stampLine +
        `export const WIKI_ENTRIES = ${stableStringify(byId(snapshot.wikiEntries ?? []))};\n`,
    },
    {
      path: "src/game/content/index.js",
      content:
        HEADER +
        stampLine +
        `export { WORLD_ENCOUNTERS } from "./world-encounters.js";\n` +
        `export { FIELD_ENCOUNTERS } from "./field-encounters.js";\n` +
        `export { QUESTS } from "./quests.js";\n` +
        `export { WIKI_ENTRIES } from "./wiki.js";\n`,
    },
  ];
}

function byId(arr) {
  const out = {};
  for (const item of arr) {
    if (item?.id) out[item.id] = item;
  }
  return out;
}

// Deterministic JSON: sort keys so the rendered files diff cleanly
// commit-over-commit even if Supabase returns rows in a different
// order. Two-space indent for readability of the generated source.
function stableStringify(value, indent = 2) {
  return JSON.stringify(value, sortedReplacer, indent);
}

function sortedReplacer(_key, value) {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    const sorted = {};
    for (const k of Object.keys(value).sort()) sorted[k] = value[k];
    return sorted;
  }
  return value;
}
