// Offline content build: table-grouped authoring JSON -> engine registries.
//
//   node scripts/build-content.mjs <input.json> [--out src/game/content]
//
// The editor's normal pipeline is Supabase -> snapshot.js -> exporter.js ->
// src/game/content/*.js. This is the same reassembly and the same rendering
// with the database taken out of the middle, so authored content can be
// built straight from a file.
//
// Why not route through the editor's importer: editor/src/lib/import.js
// rejects any effect type outside its locked list of 23, and the corpus uses
// types the ENGINE implements but that list has never been widened to include
// (ADJUST_HONOR x59, ADJUST_MENACE x24, and the newer handlers). Pushing the
// content through that funnel would mean dropping authored outcomes to
// satisfy a validator, which is backwards: the engine's contract is
// src/game/content/index.js exporting four registries, and anything that
// produces those is valid.
//
// Accepts `paramsJson` (a JSON string, the DB column shape) or `params` (an
// object) on effect rows, so the same file works for either destination.

import fs from "node:fs";
import path from "node:path";

const HEADER = `// AUTO-GENERATED by scripts/build-content.mjs.
// Do not edit by hand. Source of truth is the authoring JSON named below;
// rebuild with: node scripts/build-content.mjs <source>
// Schema: docs/content-schema-v0.1.md.
`;

const decode = (v) => {
  if (v == null || v === "") return null;
  if (typeof v !== "string") return v;
  try { return JSON.parse(v); } catch { return null; }
};

// Effect rows carry params as either `paramsJson` (string) or `params`.
const paramsOf = (row) => decode(row.paramsJson) ?? row.params ?? {};

export function assemble(doc) {
  const effectsByParent = new Map();
  for (const e of doc.effects ?? []) {
    const key = `${e.parentKind}:${e.parentId}`;
    if (!effectsByParent.has(key)) effectsByParent.set(key, []);
    effectsByParent.get(key).push({ id: e.id, type: e.type, params: paramsOf(e), ordinal: e.ordinal ?? 0 });
  }
  for (const list of effectsByParent.values()) list.sort((a, b) => a.ordinal - b.ordinal);

  // Every choice is keyed `<parentKind>:<parentId>` and every consumer looks it
  // up by the kind IT expects. A choice authored with a parentKind nobody
  // looks up is not an error anywhere — it is simply filed under a key no one
  // reads, and its beat is assembled with an empty `choices` array. That has
  // already happened once: fifteen rows written `parentKind: "beat"` instead
  // of `"quest_beat"` left NINE beats of q_tempest with no choices at all,
  // and the only symptom was those beats quietly never appearing.
  //
  // So the kinds are enumerated and anything else throws. A typo in a content
  // row should stop the build, not delete a quest.
  const CHOICE_PARENT_KINDS = new Set(["quest_beat", "world_encounter", "field_encounter"]);
  const choicesByParent = new Map();
  for (const c of doc.choices ?? []) {
    if (!CHOICE_PARENT_KINDS.has(c.parentKind)) {
      throw new Error(`assemble: choice "${c.id}" has parentKind "${c.parentKind}" — `
        + `expected one of ${[...CHOICE_PARENT_KINDS].join(", ")}. `
        + `Its parent "${c.parentId}" would be built with no choices.`);
    }
    const key = `${c.parentKind}:${c.parentId}`;
    if (!choicesByParent.has(key)) choicesByParent.set(key, []);
    choicesByParent.get(key).push({
      id: c.id, label: c.label, outcomeText: c.outcomeText ?? null,
      condition: decode(c.condition), deferredDelay: c.deferredDelay ?? null,
      ordinal: c.ordinal ?? 0,
      effects: effectsByParent.get(`choice:${c.id}`) ?? [],
    });
  }
  for (const list of choicesByParent.values()) list.sort((a, b) => a.ordinal - b.ordinal);

  const worldEncounters = (doc.world_encounters ?? []).map((r) => ({
    id: r.id, title: r.title ?? prettifyId(r.id), mode: r.mode, recipient: r.recipient ?? null,
    expiresIn: r.expiresIn ?? null, publicGroupChoice: Boolean(r.publicGroupChoice),
    art: r.art ?? null, imagePath: r.imagePath ?? null, text: r.text,
    triggerCondition: decode(r.triggerCondition), triggerStrength: decode(r.triggerStrength),
    triggerCooldown: r.triggerCooldown ?? 0,
    triggerWeight: r.triggerWeight == null ? 1 : Number(r.triggerWeight),
    placementFilter: decode(r.placementFilter),
    choices: choicesByParent.get(`world_encounter:${r.id}`) ?? [],
  }));

  const fieldEncounters = (doc.field_encounters ?? []).map((r) => ({
    id: r.id, title: r.title ?? prettifyId(r.id), copies: r.copies ?? 1,
    art: r.art ?? null, imagePath: r.imagePath ?? null, text: r.text,
    choices: choicesByParent.get(`field_encounter:${r.id}`) ?? [],
  }));

  const prereqsByBeat = new Map();
  for (const p of doc.quest_beat_prereqs ?? []) {
    if (!prereqsByBeat.has(p.beatId)) prereqsByBeat.set(p.beatId, []);
    prereqsByBeat.get(p.beatId).push(p.prereqBeatId);
  }

  const beatsByQuest = new Map();
  for (const b of doc.quest_beats ?? []) {
    if (!beatsByQuest.has(b.questId)) beatsByQuest.set(b.questId, []);
    beatsByQuest.get(b.questId).push({
      id: b.id, ordinal: b.ordinal ?? 0, prerequisites: prereqsByBeat.get(b.id) ?? [],
      deliver: b.deliver, deliverCondition: decode(b.deliverCondition),
      placementFilter: decode(b.placementFilter), mode: b.mode ?? null,
      recipient: b.recipient ?? null, art: b.art ?? null, imagePath: b.imagePath ?? null,
      text: b.text, choices: choicesByParent.get(`quest_beat:${b.id}`) ?? [],
    });
  }
  for (const list of beatsByQuest.values()) list.sort((a, b) => a.ordinal - b.ordinal);

  // An empty `choices` array is NOT itself an error — a purely narrative beat is
  // legitimate content. What was an error is a choice row that exists and fails
  // to associate: fifteen rows keyed `beat:` instead of `quest_beat:` left nine
  // beats empty, and nothing anywhere noticed.
  //
  // So the check is on ORPHANS — a choice whose parent key matches no row in
  // the document — rather than on empty beats. That still catches the typo (a
  // mis-kinded row is an orphan by definition) and leaves the author free to
  // write a beat that is only text.
  const knownParents = new Set();
  for (const b of doc.quest_beats ?? []) knownParents.add(`quest_beat:${b.id}`);
  for (const r of doc.world_encounters ?? []) knownParents.add(`world_encounter:${r.id}`);
  for (const r of doc.field_encounters ?? []) knownParents.add(`field_encounter:${r.id}`);
  const orphans = (doc.choices ?? [])
    .filter((c) => !knownParents.has(`${c.parentKind}:${c.parentId}`))
    .map((c) => `${c.id} -> ${c.parentKind}:${c.parentId}`);
  if (orphans.length) {
    throw new Error(`assemble: ${orphans.length} choice row(s) point at a parent that does `
      + `not exist, so they will never be offered: ${orphans.join(", ")}`);
  }

  const quests = (doc.quests ?? []).map((r) => ({
    id: r.id, title: r.title || prettifyId(r.id), mode: r.mode,
    beats: beatsByQuest.get(r.id) ?? [],
    completion: {
      rewardForClaimant: effectsByParent.get(`quest_claim_reward:${r.id}`) ?? [],
      sharedSideEffects: effectsByParent.get(`quest_shared_reward:${r.id}`) ?? [],
    },
  }));

  const wikiEntries = (doc.wiki_entries ?? []).map((r) => ({
    id: r.id, term: r.term, aliases: decode(r.aliases) ?? [],
    category: r.category ?? null, body: r.body, imagePath: r.imagePath ?? null,
  }));

  return { worldEncounters, fieldEncounters, quests, wikiEntries };
}

function prettifyId(id) {
  let s = String(id || "").replace(/^(fe|we|q|qb|quest|beat)_/i, "");
  return s.replace(/[_-]+/g, " ").trim().replace(/\b\w/g, (c) => c.toUpperCase());
}

const byId = (arr) => Object.fromEntries(arr.filter((x) => x?.id).map((x) => [x.id, x]));

// Deterministic output: sorted keys, so a rebuild diffs cleanly.
const stable = (v) => JSON.stringify(v, (_k, val) =>
  val && typeof val === "object" && !Array.isArray(val)
    ? Object.fromEntries(Object.keys(val).sort().map((k) => [k, val[k]]))
    : val, 2);

export function render(snapshot, sourceName) {
  const stamp = `// Source: ${sourceName}\n// Generated at ${new Date().toISOString()}.\n\n`;
  const head = HEADER + stamp;
  return [
    ["world-encounters.js", `${head}export const WORLD_ENCOUNTERS = ${stable(byId(snapshot.worldEncounters))};\n`],
    ["field-encounters.js", `${head}export const FIELD_ENCOUNTERS = ${stable(byId(snapshot.fieldEncounters))};\n`],
    ["quests.js",           `${head}export const QUESTS = ${stable(byId(snapshot.quests))};\n`],
    ["wiki.js",             `${head}export const WIKI_ENTRIES = ${stable(byId(snapshot.wikiEntries))};\n`],
    ["index.js", head +
      `export { WORLD_ENCOUNTERS } from "./world-encounters.js";\n` +
      `export { FIELD_ENCOUNTERS } from "./field-encounters.js";\n` +
      `export { QUESTS } from "./quests.js";\n` +
      `export { WIKI_ENTRIES } from "./wiki.js";\n`],
  ];
}

const isMain = import.meta.url === `file://${process.argv[1]}`.replace(/\\/g, "/")
  || process.argv[1]?.endsWith("build-content.mjs");
if (isMain) {
  const input = process.argv[2];
  if (!input) { console.error("usage: node scripts/build-content.mjs <input.json> [--out DIR]"); process.exit(1); }
  const outIdx = process.argv.indexOf("--out");
  const outDir = outIdx > 0 ? process.argv[outIdx + 1] : "src/game/content";
  const doc = JSON.parse(fs.readFileSync(input, "utf8"));
  const snap = assemble(doc);
  fs.mkdirSync(outDir, { recursive: true });
  for (const [name, body] of render(snap, path.basename(input))) {
    fs.writeFileSync(path.join(outDir, name), body);
  }
  console.log(`built ${snap.worldEncounters.length} world, ${snap.fieldEncounters.length} field, `
    + `${snap.quests.length} quests, ${snap.wikiEntries.length} wiki -> ${outDir}`);
}
